### ISSUE TITLE
Triggar o CI novamente, quando faz o auto-update

### ISSUE THREAD

**Issue by jacks-pp** [jacolpn/git-actions-study#38]
Commit generated in one workflow does not trigger pull_request workflow
Commits are not triggering CI actions

**Comment by jacks-pp** [comment]
https://github.com/EndBug/add-and-commit?tab=readme-ov-file#the-commit-from-the-action-is-not-triggering-ci

**Comment by jacks-pp** [comment]
https://github.com/orgs/community/discussions/27146

**Comment by jacks-pp** [comment]
solução:  Incluir o token na action de checkout


- name: Checkout da branch
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_AUTH_TOKEN }}

**Comment by jacks-pp** [comment]
I solve this problem adding token in checkout/actions
```
  - name: Checkout da branch
          uses: actions/checkout@v3
          with:
            token: ${{ env.GITHUB_AUTH_TOKEN }}
```
